### ISSUE TITLE
Internal Server Error on NLP service

### ISSUE THREAD

**Issue by yoshiask** [CopticScriptorium/CopticScriptorium.github.io#15]
When attempting to use the [Coptic NLP Service](https://tools.copticscriptorium.org/coptic-nlp/), it loads for a second after clicking "Process", but then always returns an HTTP 500 error. It fails no matter the input, even on the default settings and text.

![image](https://github.com/user-attachments/assets/c7a26050-4b95-4a64-9d81-fee16c79155d)

**Comment by amir-zeldes** [comment]
Thanks for reporting (though note Coptic-NLP has its own repo/issue tracker [here](https://github.com/CopticScriptorium/coptic-nlp/))

I think I have this fixed now, please let me know if you run into any more errors!

**Comment by yoshiask** [comment]
Works great now, thanks! Sorry about being in the wrong repo, I thought it should be reported here because it seemed like the website was broken and not the tool itself.

As an aside, congratulations on launching Bohairic support! 🎉

**Comment by amir-zeldes** [comment]
No worries, and thanks for the congratulations - we are still far behind on quality for Bohairic compared to Sahidic, but we are working hard to improve the situation and release more data and tools!
