### ISSUE TITLE
Citation guidelines

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/CopticScriptorium.github.io#5]
Please create the page for the citation guidelines here.  Anything committed to the master branch automatically populates on the website.  If you want to experiment, you can create a separate branch.
Before adding the citation guidelines:  Please switch the order of the names on the project citation (Schroeder first, then Zeldes).  Then we need to:
- Create a page.
- Add the page to the dropdown menu under documentation.  
- Add a link to the documentation quick guide.  
- Put the project documentation on the main index page with a link to the page for full citation guidelines.
After that we can tackle data.scriptorium.org?  I'm thinking keep it simple on data.scriptorium.org with a link to the main guidelines page.  As much as possible, I'd like everything in one place so if we change things, we don't have to change five pages.
Let me know if you have any questions about the files.

**Comment by eplatte** [comment]
1-3 finished. For 4, do you mean add a link to documentation in a paragraph on the index page, and also for the citation guidelines? Following up via email.

**Comment by ctschroeder** [comment]
for 4:  I mean somewhere on our main index page we should have the instructions about how to cite the project. E.g. "To cite this project (insert a colon or something something narratively coherent?) Caroline T. Schroeder, Amir Zeldes, et al., _Coptic SCRIPTORIUM_, 2013-2016, http://copticscriptorium.org." and then something about a link to full citation guidelines.  Just so it's obvious on the splash page how to cite and refer to the project.
I think EpiDoc's main page may have a how to cite EpiDoc that is a model.
For data.copticscriptorium.org:  the html is in the https://github.com/CopticScriptorium/cts repository.  But the HTML doesn't automatically update (unlike the main domain).  I will have to show you how to transfer the html files.

**Comment by eplatte** [comment]
OK sounds good. I'll add something to the index page later tonight. 
Also, could you check the formatting on copticscriptorium.org/citation-guidelines to make sure it looks OK? For the most part, I followed the formatting of the google doc, except a few small changes because of html.
Finally, when I initially added the link to the drop down menu, I called it "citation guidelines," but it caused the menu to display badly (and I couldn't really figure out why). Does "citation" make sense, or should I use a different word?

**Comment by eplatte** [comment]
I added the citation guidelines to the index. 
I also found the css to change the way the documentation menu displays, but I still think it looks better with "citation" rather than "citation guidelines." If there's a better word, though, let me know!
