### ISSUE TITLE
Create contact-us mechanism

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/CopticScriptorium.github.io#7]
Consider form or email? put on About page or elsewhere? Also should encourage folks with GitHub accounts submit issues.

@eplatte is this something you could add to your task list?

**Comment by eplatte** [comment]
I can do this. I'd rather go with an email than a form. I remember that we have an email address connected to the website, right? Do you know what it is? I'll add it to the About page with information about GitHub, too.

**Comment by eplatte** [comment]
I've added a link to our email address and a suggestion to add an issue on GitHub to to bottom of the about page. I usually look for contact at the bottom of a page, but I'm afraid it's lost here. Let me know what you think. I'm happy to move/change anything. Maybe we should also add contact info to the FAQ page and/or the documentation wiki?

**Comment by ctschroeder** [comment]
I agree that it gets a little lost.  Maybe after the description/before 
the "Support for..." para? Many thanks.

**Comment by eplatte** [comment]
OK moved. I think it looks better. Thanks!
